language: python
python:
- '2.7'
install: pip install tox
script: tox
notifications:
  email:
  - pupssman@gmail.com
deploy:
  provider: pypi
  user: pupssman
  password:
    secure: Z1u/x+C58b//XdOcV/r5xzbho/QrbjLWz9LVVZIE2DVfSw8js4NIAiHZjkR2QlNaPZX3H6aM8D2ulfKBiCe45oOVoPjz4QENneOdAdBvWGr6E6t8NExj33j8hSSS4WuLtKbZtmkD8oX/6TrUcUtJALo+i9bKmAd1FP43xTj3zY4=
  on:
    tags: true
    all_branches: true
